<!-- Error = An Object that is created to represent a problem that occurs 
          Occur often with user input or establising a connection

 try {} = ecloses code that might potentially causes an error 
 catch{} = catch and handle any thrown Error from try {}
 finally {} = always Executes. used mostly for clean up  -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ErrorHandling</title>
</head>
<body>
    <script>
       try {
    const dividend =Number(window.prompt("enter a dividend: "));
    const divisor = Number(window.prompt("enter the divisor: "));

    if(divisor == 0){
        throw new Error("You cant divide by Zero");
    }
    if(isNaN(dividend)|| isNaN(divisor)){
        throw new Error("values must be a number");
    }
    
    const result=dividend/divisor
    console.log(result);
    
}
catch(error){
    console.error(error);
}
finally{

    // close file , connections , release resources
    console.log("Finally : this always executed");
    
}
console.log("you have reached the end!"); 
    </script>
</body>
</html>

